apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    tenantId: 570057f4-73ef-41c8-bcbb-08db2fc15c2b
    userAssignedIdentityID: ab74d8ef-7aa4-41c5-8ac4-399ff7134fbf # Set the clientID of the kubelet identity ID
    keyvaultName: akv-xpto
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key1
          objectType: key
          objectVersion: ""
        - |
          objectName: cert1
          objectType: cert
          objectVersion: ""